<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('LmcAdmin - LM-Commons')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') 
                                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') 
    ?>

    <!-- styles -->
    <?php echo $this->headLink()->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css',
        'screen', false, [
            'integrity' => 'sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH',
            'crossorigin' => 'anonymous'
        ]
    );
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript();?>

  </head>

  <body>

    <nav class="navbar navbar-expand-md bg-body-tertiary mb-4" role="navigation">
        <div class="container">
            <div class="navbar-brand">Admin</div>
            <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <?php echo $this->navigation('admin_navigation')
                    ->menu()
                    ->setUlClass('nav navbar-nav')
                    ->setMaxDepth(0)
                    ->setRenderInvisible(false)?>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2020 - <?php echo date('Y') ?> by the <a href="https://lm-commons.github.io">LM-Commons Organization</a></p>
      </footer>

    </div> <!-- /container -->

    <?= $this->inlineScript()
        ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js',
            'text/javascript', [
                'integrity' => 'sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz',
                'crossorigin' => 'anonymous'
            ]
        ) ?>

  </body>
</html>
